### ISSUE TITLE
Doesn't support new AWS regions

### ISSUE THREAD

**Issue by jyoungs** [anomalizer/ngx_aws_auth#14]
Re: http://docs.aws.amazon.com/AmazonS3/latest/dev/auth-request-sig-v2.html

"...Amazon S3 now supports the latest Signature Version 4, which is supported in all regions; it is the only version supported for new AWS regions..."

Would be better if this used AuthV4:
http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html

**Comment by bebud** [comment]
+1

**Comment by anomalizer** [comment]
ACKed. I might need another 2-4 weeks before I get to this. Any pull requests are welcome.

**Comment by zyq2007** [comment]
+1

**Comment by andrea-spoldi** [comment]
+1

**Comment by xposix** [comment]
+1

**Comment by anomalizer** [comment]
Update: I am working on a new branch (Authv4-dev) that is not yet complete to address this. Should have this ready in a couple of weeks time.

**Comment by anomalizer** [comment]
Please start watching the branch **AuthV4**. It now has the most basic support for new regions

**Comment by anomalizer** [comment]
Please try the new code on master. It is on V4 protocol and hence should work on new regions

**Comment by CpuID** [comment]
Safe to close based on the README @anomalizer ?
