### ISSUE TITLE
SignatureDoesNotMatch

### ISSUE THREAD

**Issue by y2kkarthik** [anomalizer/ngx_aws_auth#54]
Hello,

I am facing SignatureDoesNotMatch error although I have followed same configurations suggested in this plugin manual.

nginx.conf
----------------------------------------------

server {
        listen 80;
        aws_access_key XXXX;
        aws_key_scope 20181116/us-east-1/s3/aws4_request;
        aws_signing_key XXXX;
        aws_s3_bucket example-nginx;

location / {
            aws_sign;
            proxy_pass http://example-nginx.s3.amazonaws.com;
  }
}

Please advise if I am making anything wrong. 

PS: I am using aws secret key for signing key generation and aws access key for aws_access_key 

Regards,
Karthik

**Comment by leffuy** [comment]
Was this ever solved? I'm having the same issue using the documentation 1:1

Was this project abandoned and then something changed on amazon's side?
